### ISSUE TITLE
problem loading java

### ISSUE THREAD

**Issue by rajanikanthnmsu** [njdbickhart/RAPTR-SV#1]
Dear Derek,
I am Raj, and trying to use your program. I am getting some problem in loading.
could you please check below and see what might be the problem.

[ spru@/scratch/ragovindarajulu/sorg_intraspecific_reads/bamfiles ] $ java -jar /shared/software/genomics/RAPTR-SV-0.0.15/store/RAPTR-SV.jar preprocess -i b35.sam.bam.sorted.bam -o b35rap -r Sorbi1_assembly_scaffolds_hardmasked.fasta -g -d
[MAIN] Command line arguments supplied: 
preprocess -i b35.sam.bam.sorted.bam -o b35rap -r Sorbi1_assembly_scaffolds_hardmasked.fasta -g -d
[MAIN] Debug flag set to: true
[MAIN] RAPTR-SV version: 0.0.15
[MAIN] RAPTR-SV preprocess mode selected.
Exception in thread "main" java.lang.NullPointerException
at workers.BamMetadataGeneration.ScanFile(BamMetadataGeneration.java:107)
at modes.PreprocessMode.run(PreprocessMode.java:91)
at workers.RPSRmain.main(RPSRmain.java:69

**Comment by njdbickhart** [comment]
Hello Raj,

As we discussed, there was an issue with the readgroup lines in the BAM. I'm going to keep this issue open so that I improve the core program with better exception handling for cases like this.

Thanks,
Derek
